const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveConfig: (cfg) => ipcRenderer.invoke('save-config', cfg),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  testYtApiKey: (apiKey) => ipcRenderer.invoke('test-yt-api-key', apiKey),
  getPlaylists: () => ipcRenderer.invoke('get-playlists'),
  savePlaylists: (pl) => ipcRenderer.invoke('save-playlists', pl),
  getStream: (ytUrl, quality) => ipcRenderer.invoke('get-stream', ytUrl, quality),
  search: (query) => ipcRenderer.invoke('search', query),
  getVideoInfo: (ytUrl) => ipcRenderer.invoke('get-video-info', ytUrl),
  openSettings: () => ipcRenderer.invoke('open-settings'),
  closeSettings: () => ipcRenderer.invoke('close-settings'),
  toggleAlwaysOnTop: () => ipcRenderer.invoke('toggle-always-on-top'),
  setAlwaysOnTop: (val) => ipcRenderer.invoke('set-always-on-top', val),
  getLoginItem: () => ipcRenderer.invoke('get-login-item'),
  setLoginItem: (val) => ipcRenderer.invoke('set-login-item', val),
  minimize: () => ipcRenderer.invoke('minimize'),
  closeApp: () => ipcRenderer.invoke('close-app'),
  quitApp: () => ipcRenderer.invoke('quit-app'),
  toggleFillHeight: () => ipcRenderer.invoke('toggle-fill-height'),
  checkYtdlp: () => ipcRenderer.invoke('check-ytdlp'),
  getLyrics: (ytUrl, title, channel, duration) => ipcRenderer.invoke('get-lyrics', ytUrl, title, channel, duration),
  searchLyricsManual: (ytUrl, artist, title, duration) => ipcRenderer.invoke('search-lyrics-manual', ytUrl, artist, title, duration),
  saveManualSync: (ytUrl, syncLines) => ipcRenderer.invoke('save-manual-sync', ytUrl, syncLines),
  onSettingsClosed: (cb) => ipcRenderer.on('settings-closed', cb),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', cb),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', cb),
  onUpdateNotAvailable: (cb) => ipcRenderer.on('update-not-available', cb),
  onUpdateError: (cb) => ipcRenderer.on('update-error', (_, msg) => cb(msg)),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  onOpenSettings: (cb) => ipcRenderer.on('open-settings', cb),
  onOpenAbout: (cb) => ipcRenderer.on('open-about', cb),
  toggleMainWindow: () => ipcRenderer.invoke('toggle-main-window'),
  tabDragStart: () => ipcRenderer.invoke('tab-drag-start'),
  tabDragMove: (dy) => ipcRenderer.invoke('tab-drag-move', dy),
  tabDragEnd: (dy) => ipcRenderer.invoke('tab-drag-end', dy),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  onSetTheme: (cb) => ipcRenderer.on('set-theme', (_, theme) => cb(theme)),
  // 계정(2026-08-07 추가)
  getActiveAccount: () => ipcRenderer.invoke('account-get-active'),
  registerAccount: (name, pin) => ipcRenderer.invoke('account-register', name, pin),
  changeAccountName: (newName) => ipcRenderer.invoke('account-change-name', newName),
  changeAccountPin: (currentPin, newPin, resetMode) => ipcRenderer.invoke('account-change-pin', currentPin, newPin, resetMode),
  setPersonalize: (on) => ipcRenderer.invoke('account-set-personalize', on),
  toggleChannelBlock: (channel) => ipcRenderer.invoke('toggle-channel-block', channel),
  getBlockedChannels: () => ipcRenderer.invoke('get-blocked-channels'),
  // 추천(2026-08-07 추가)
  getRecommendations: (seedYtUrl, excludeIds, count) => ipcRenderer.invoke('get-recommendations', seedYtUrl, excludeIds, count),
  recordPlayEvent: (ytUrl, meta, eventType) => ipcRenderer.invoke('record-play-event', ytUrl, meta, eventType)
});
